name: CI
on:
  workflow_dispatch:
    inputs: 
      logLevel: 
        description: 'Log level'      
        required: true 
        default: 'warning' 
      tags: 
        description: 'Test scenario tags' 
      environment:
        type: environment
        description: Select the environment
      boolean:
        type: boolean
        description: True or False
      choice:
        type: choice
        description: Make a choice
        options:
        - foo
        - bar
        - baz

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v3
      
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo "Log level: ${{ github.event.inputs.logLevel }}" 
          echo "Tags: ${{ github.event.inputs.tags }}" 
          echo "environment is ${{ github.event.inputs.environment }}"
          echo "boolean is ${{ github.event.inputs.boolean }}"
          echo "choice is ${{ github.event.inputs.choice }}"
  
  job2:
    runs-on: windows-latest
    needs: build
    # needs: [job1, job2]
    steps:
      - name: step3:-Automatically install the libraries.
        run: |
          echo run over!!!!

